version: '3'

services:

  db:
    hostname: halirant_db
    image: geldata/gel:latest
    ports:
      - "5656:5656"
    environment:
      - GEL_SERVER_PASSWORD=secret
      - GEL_SERVER_TLS_CERT_MODE=generate_self_signed
      - GEL_SERVER_SECURITY=insecure_dev_mode
    volumes:
      - db_data:/var/lib/gel/data
    networks:
      - db_net
    restart: unless-stopped
  
  backend:
    hostname: halirant_back
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - GEL_DSN=gel://admin:secret@halirant_db:5656
    networks:
      - db_net
    restart: unless-stopped
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8420:80"
    networks: # TODO: Rm if needed
      - db_net
    restart: unless-stopped


  
volumes:
  db_data:

networks:
  db_net:
    driver: bridge
