[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.1",
    "gel>=2.0.1",
    "shapely>=2.0.7",
    "fastapi[standard]",
]
